<!DOCTYPE html>
<html lang="pt_BR">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="Administração igreja Quilombo">
    <meta name="author" content="">
    <link rel="icon" href="favicon.ico">
    <title>Dashboard Igreja Quilombo</title>
    <link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" rel="stylesheet">
    <link href="/dashboard.css" rel="stylesheet">
    <script src="/ie-emulation-modes-warning.js"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
  </head>

  <body>
  <div>
    <nav class="navbar navbar-inverse navbar-fixed-top">
      <div class="container-fluid">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="/membros">Igreja Quilombo</a>
        </div>
        <div id="navbar" class="navbar-collapse collapse">
          <ul class="nav navbar-nav navbar-right">
            <li><a href="#">Sair</a></li>
          </ul>
        </div>
      </div>
    </nav>
    <div class="container-fluid">
      <div class="row">
        <div class="col-sm-3 col-md-2 sidebar">
          <ul id="navList" class="nav nav-sidebar">
            <li id="membros" class="" ><a href="/membros">Membros <span class="sr-only">(current)</span></a></li>
            <li id="add"      ><a href="/add">Adicionar</a></li>
            <li id="ano"      ><a href="/ano">Adicionar valor ano</a></li>
          </ul>
          <ul class="nav nav-sidebar">
            <li><a href="/bilhete">Bilhetes</a></li>
            <li><a href="/bilhete">Relatorio Anual</a></li>
            <li><a href="/bilhete">Perguntas Pasta</a></li>
          </ul>
        </div>
        <div class="col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2 main">
		    <?=$data['content'];?>
        </div>
        </div>
      </div>
    </div>
  </body>
</html>
