<form class="form-horizontal" method="post" action="<?php echo htmlspecialchars($_SERVER["REQUEST_URI"]);?>">
	<div class="row">
		<div class="form-group col-xs-10" style="padding-right: 0;">
			<textarea class="form-control" name="mensagem" rows="5" value="<?php echo $mensagem?>"></textarea>
		</div>
	</div>
	<br><br>
	<div class="row">
		<div class="form-group col-xs-5" style="padding-right: 0;">
			<label class="form-control">Numero de colunas por página: </label>
		</div>
		<div class="form-group col-xs-4" style="padding-right: 0;">
			<input class="form-control" name="colunas" value="3"></input>
		</div>
		<div class="form-group col-xs-2">
			<input class="form-control" class="button" type="submit" name="submit" value="Imprimir">  
		</div>
	</div>
</form>

